parameters:
  database_driver: pdo_mysql
  database_host: 127.0.0.1
  database_port: null
  database_name: suplink
  database_user: root
  database_password: 2212Load
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: null
  mailer_password: null
  locale: en
  secret: e9dfab520ce69bffe0798807d8e52770
  database_path: null
