suplink_link:
    resource: "@SuplinkLinkBundle/Resources/config/routing.yml"
    prefix:   /

suplink_home:
    resource: "@SuplinkHomeBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

_welcome:
    pattern:  /
    defaults: { _controller: SuplinkHomeBundle:Default:index }