jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path:     fos_user_security_login
                check_path:     fos_user_security_check               
                default_target_path: /dashboard/index
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
            anonymous:    true

    access_control:
        - { path: ^/login$, access: "isAnonymous()" }
        - { path: ^/register, access: "isAnonymous()" }
        - { path: ^/resetting, access: "isAnonymous()" }
        - { path: ^/dashboard, access: "hasRole('ROLE_USER') or hasRole('ROLE_ADMIN')" }
        - { path: ^/admin/, role: ROLE_ADMIN }

