parameters:
#    suplink_link.example.class: Suplink\LinkBundle\Example

services:
#    suplink_link.example:
#        class: %suplink_link.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
